apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  namespace: monitoring
type: Opaque
data:
  INFLUXDB_DATABASE: c3RhdGljdGljcw==
  INFLUXDB_USERNAME: cm9vdA==
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_HOST: aW5mbHV4ZGI=
