{
 "title": "System",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active Registrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "query": "SELECT last(\"count\") FROM \"registrations\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Total Minutes  (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Minutes  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Recordings (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Recording Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Attempts (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "<>", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Call Attempts (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voicemails  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voicemail Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Level 3 Alarms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "alarms",
     "select": [
      [
       { "params": [ "msg" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Subscribers, Registrations and Sessions",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "tenantId" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "subscnts",
     "query": "SELECT count(\"msg\") FROM \"alarms\" WHERE $timeFilter GROUP BY \"severity\", \"serverName\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "subscribers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now() - 24h" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "tenantId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "registrations" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now() - 24h" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "tenantId" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") AS sessions FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now() - 24h" }
     ]
    }
   ]
  },
  {
   "title": "Active Sessions vs Subscribers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Subscribers",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "subscnts",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "subscribers" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Sessions",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sessions" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Sessions vs Registrations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sessions",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Registrations",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "query": "SELECT mean(\"count\") FROM \"registrations\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Attempts vs Registrations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Call Attempts",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "callcounts",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Registrations",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Sessions vs CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sessions",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverinfo",
     "query": "SELECT mean(\"hcpu\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(10s), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "hcpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "serverinfo",
     "select": [
      [
       { "params": [ "rtime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverinfo",
     "select": [
      [
       { "params": [ "fmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory vs CPU (24h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "serverinfo",
     "query": "SELECT mean(\"hcpu\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(10s), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "hcpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serverId", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverinfo",
     "query": "\nSELECT mean(\"fmem\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(1s), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "fmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serverId", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Diskspace",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "serverinfo",
     "select": [
      [
       { "params": [ "fdisk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serverId", "operator": "=", "value": "3" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Diskspace, VM Count, VM Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "VM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "vm",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Diskspace",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverinfo",
     "query": "SELECT mean(\"fdisk\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(10s), \"host\"",
     "select": [
      [
       { "params": [ "fdisk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VMSize",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"size\")  / 1000000) FROM \"vm\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Switch 1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "serverinfo",
     "query": "SELECT mean(\"hcpu\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "hcpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serverId", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Call Inbound Attempts (1 hr buckets) vs CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CallAttempts",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"count\") FROM \"callcounts\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"hcpu\") FROM \"serverinfo\" WHERE (\"serverId\" = '3') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 } },
  {
   "title": "PowerNova Alarms",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "severity" ], "type": "tag" },
      { "params": [ "serverName" ], "type": "tag" }
     ],
     "measurement": "alarms",
     "query": "SELECT count(\"msg\") FROM \"alarms\" WHERE $timeFilter GROUP BY \"severity\", \"serverName\"",
     "select": [
      [
       { "params": [ "msg" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "repeat": "varseverity",
   "targets": [
    {
     "measurement": "alarms",
     "query": "SELECT severity,  alarmType, alarmId, switchId, serverId, serverName,  msg FROM \"alarms\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alarmId" ], "type": "field" }
      ],
      [
       { "params": [ "msg" ], "type": "field" }
      ],
      [
       { "params": [ "severity" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}