{
 "title": "Tenant",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CompanyId", "label": "Company", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Active Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "confcount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "0" }
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Call Inbound Attempts (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Total Inbound Minutes  (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Voicemails  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recordings (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Active Conference Participants",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "partycount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "0" }
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active Registrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "query": "SELECT last(\"count\") FROM \"registrations\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Call Outbound Attempts (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Total Outbound Minutes  (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Voicemail Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recording Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Active Conference Participant Minutes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "partydur" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "0" }
     ],
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active Sessions vs Registrations (1hr buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sessions",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeSessions",
     "query": "SELECT last(\"count\") FROM \"activeSessions\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Registrations",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "registrations",
     "query": "SELECT mean(\"count\") FROM \"registrations\" WHERE $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Active Conference Participants/Total Minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Participant Minutes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT mean(\"count\") FROM \"confcounts\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  $__timeGroup(startTime, '5m', NULL) AS time,\n  COUNT(*) AS Conferences\nFROM\n  conferenceCdrs\nWHERE\n  $__timeFilter(startTime)\n  GROUP BY $__timeGroup(startTime, '5m', NULL)\n  "
    },
    {
     "alias": "Active Participants",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT sum(\"count\") AS \"partycounts\" FROM \"confpartycounts\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "partycount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "partycounts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Call Attempts (1 hr buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Outbound-Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"count\") FROM \"callcounts\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "cntConnected" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Outbound-NotConnected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"cntTotal\") - sum(\"cntConnected\") FROM \"tenant2\" WHERE (\"tenantId\" = '$CompanyId') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Inbound-Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"count\") FROM \"callcounts\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "cntConnected" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Inbound-NotConnected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"cntTotal\") - sum(\"cntConnected\") FROM \"tenant2\" WHERE (\"toTenantId\" = '$CompanyId') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "avgTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Active Conferences",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Participant Minutes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeConf",
     "query": "SELECT mean(\"count\") FROM \"confcounts\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  $__timeGroup(startTime, '5m', NULL) AS time,\n  COUNT(*) AS Conferences\nFROM\n  conferenceCdrs\nWHERE\n  $__timeFilter(startTime)\n  GROUP BY $__timeGroup(startTime, '5m', NULL)\n  "
    }
   ]
  },
  {
   "title": "Total Minutes (1hr buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total Outbound Minutes",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Total Inbound Minutes",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "tenant2",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Conference Participants/Total Minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Participants",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "confpartycounts",
     "query": "SELECT sum(\"count\") AS \"partycounts\" FROM \"confpartycounts\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "partycounts" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Total Participant Minutes",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "confpartydur",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average ICE Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(created, '5m', NULL) AS time,\n  AVG(milliseconds) / 1000 AS OutboundICECollection\nFROM\n  UOWtimers\nWHERE\n  $__timeFilter(created) AND (UOWType = 5)\n  GROUP BY $__timeGroup(created, '5m', NULL)\n  "
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(created, '5m', NULL) AS time,\n  AVG(milliseconds) / 1000 AS InboundICECollection\nFROM\n  UOWtimers\nWHERE\n  $__timeFilter(created) AND (UOWType = 9)\n  GROUP BY $__timeGroup(created, '5m', NULL)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(created, '5m', NULL) AS time,\n  AVG(milliseconds) / 1000 AS ConferenceICECollection\nFROM\n  UOWtimers\nWHERE\n  $__timeFilter(created) AND (UOWType = 23)\n  GROUP BY $__timeGroup(created, '5m', NULL)"
    }
   ]
  },
  {
   "title": "Log-In (24h)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(created, '1h', NULL) AS time,\n  COUNT(*) AS Successful\nFROM\n  subscriberLoginTransaction\nWHERE\n  $__timeFilter(created) AND created IS NOT NULL\n  AND failed = 0\n  GROUP BY $__timeGroup(created, '1h', NULL)\n  "
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(created, '1h', NULL) AS time,\n  COUNT(*) AS Failed\nFROM\n  subscriberLoginTransaction\nWHERE\n  $__timeFilter(created) AND created IS NOT NULL\n  AND failed = 1\n  GROUP BY $__timeGroup(created, '1h', NULL)\n  "
    }
   ]
  },
  {
   "title": "VM Count vs VM Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "VM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "vm",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "VMSize",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"size\")  / 1000000) FROM \"vm\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recording Count vs Call Recording Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Call Recordings",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "rc",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    },
    {
     "alias": "Call Recording Size",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"size\")  / 1000000) FROM \"vm\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Call Completion Percentage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Connected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tenant2",
     "query": "SELECT SUM(\"cntConnected\") AS Connected FROM \"tenant2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "cntConnected" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "cntTotal" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tenant2",
     "query": "SELECT SUM(\"cntTotal\") -  SUM(\"cntConnected\") AS Failed FROM \"tenant2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Ten Extensions (24h)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 36 },
   "targets": [
    {
     "measurement": "topten",
     "select": [
      [
       { "params": [ "rank" ], "type": "field" },
       { "params": [ "Rank" ], "type": "alias" }
      ],
      [
       { "params": [ "subscriberId" ], "type": "field" },
       { "params": [ "Subscriber" ], "type": "alias" }
      ],
      [
       { "params": [ "firstName" ], "type": "field" },
       { "params": [ "First Name" ], "type": "alias" }
      ],
      [
       { "params": [ "lastName" ], "type": "field" },
       { "params": [ "Last Name" ], "type": "alias" }
      ],
      [
       { "params": [ "durTotal" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" },
       { "params": [ "Duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" }
     ]
    }
   ]
  },
  {
   "title": "Top Ten Conference Extensions (24h)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 12, "y": 36 },
   "targets": [
    {
     "measurement": "toptenconf",
     "select": [
      [
       { "params": [ "rank" ], "type": "field" },
       { "params": [ "Rank" ], "type": "alias" }
      ],
      [
       { "params": [ "subscriberId" ], "type": "field" },
       { "params": [ "Subscriber" ], "type": "alias" }
      ],
      [
       { "params": [ "firstName" ], "type": "field" },
       { "params": [ "First Name" ], "type": "alias" }
      ],
      [
       { "params": [ "lastName" ], "type": "field" },
       { "params": [ "Last Name" ], "type": "alias" }
      ],
      [
       { "params": [ "durTotal" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" },
       { "params": [ "Duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "0" }
     ]
    }
   ]
  }
 ]
}