{
 "title": "Subscriber",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CompanyId", "label": "Company", "query": "1" },
   { "name": "SubscriberId", "label": "Subscriber", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Call Inbound Attempts (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "cdr",
     "query": "SELECT count(\"sipcid\") FROM \"cdr\" WHERE (\"tenantId\" = '$CompanyId' AND \"fromSubId\" = '$SubscriberId' OR \"toSubId\" = '$SubscriberId') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "toSubId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Call Outbound Attempts (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "cdr",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "fromTenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "fromSubId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Total Inbound Minutes  (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "cdr",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "toTenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "toSubId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Total Outbound Minutes  (1h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "cdr",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "durTotal" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "fromTenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "fromSubId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recordings (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recording Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Voicemails  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Voicemail Size  (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"total\") / 60) AS minutes FROM \"avgcalldur\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Call Counts (24h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Outbound-Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "fromSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Outbound-Not Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "fromSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "False" }
     ]
    },
    {
     "alias": "Inbound-Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "query": "SELECT count(\"sipcid\") FROM \"cdr\" WHERE (\"toSubId\" = '$SubscriberId') AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "toSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Inbound-Not Connected",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "query": "SELECT count(\"sipcid\") FROM \"cdr\" WHERE (\"toSubId\" = '$SubscriberId' AND \"connected\" = 'True') AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "sipcid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "toSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "Total Minutes (24h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Outbound",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "fromSubId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "query": "SELECT (tmEnd-tmConnect)/10000000 AS dur FROM \"cdr\" WHERE $timeFilter GROUP BY time($__interval) fill(null),  toSubId",
     "select": [
      [
       { "params": [ "durConnect" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "fromSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cdr",
     "select": [
      [
       { "params": [ "durConnect" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "toSubId", "operator": "=", "value": "$SubscriberId" },
      { "condition": "AND", "key": "connected", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "VM Count vs VM Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "VM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "vm",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    },
    {
     "alias": "VMSize",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vm",
     "query": "SELECT (sum(\"size\")  / 1000000) FROM \"vm\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  },
  {
   "title": "Call Recording Count vs Call Recording Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Call Recordings",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "rc",
     "query": "SELECT sum(\"count\") FROM \"vm\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    },
    {
     "alias": "Call Recording Size",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rc",
     "query": "SELECT (sum(\"size\")  / 1000000) FROM \"vm\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tenantId", "operator": "=", "value": "$CompanyId" },
      { "condition": "AND", "key": "subscriberId", "operator": "=", "value": "$SubscriberId" }
     ]
    }
   ]
  }
 ]
}