apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: monitoring
spec:
  storageClassName: buzz-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
